name: CI (Windows)

# Windows tests are flaky, so this workflow is only run manually.
on:
  workflow_dispatch:

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    with:
      runner: windows-latest
      report-name: playwright-artifacts-windows
