name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run unit-test

      - uses: taiki-e/install-action@v2
        with:
          tool: jj-cli

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Playwright tests
        run: npm run playwright-test
